import { GhostExport } from "../../types/ghost";

const formatDate = (dateInput: string | number | Date): string => {
    const d = new Date(dateInput);
    if (isNaN(d.getTime())) return "0000-00-00 00:00:00";
    return d.toISOString().replace('T', ' ').substring(0, 19);
};

export const convertGhostToWp = (ghostData: GhostExport): string => {
    const data = ghostData.db[0].data;
    const posts = data.posts;
    const tags = data.tags;
    const posts_tags = data.posts_tags || [];
    const users = data.users || [];
    const posts_authors = data.posts_authors || [];

    const tagMap = new Map(tags.map(t => [t.id, t]));
    const userMap = new Map(users.map(u => [u.id, u]));

    let xml = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"
  xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
  xmlns:content="http://purl.org/rss/1.0/modules/content/"
  xmlns:wfw="http://wellformedweb.org/CommentAPI/"
  xmlns:dc="http://purl.org/dc/elements/1.1/"
  xmlns:wp="http://wordpress.org/export/1.2/">
  <channel>
    <title>Converted from Ghost</title>
    <link>https://ghost.org</link>
    <description>Generated by wp2ghost</description>
    <pubDate>${new Date().toUTCString()}</pubDate>
    <language>en-US</language>
    <wp:wxr_version>1.2</wp:wxr_version>
`;

    // Add Authors
    users.forEach(user => {
        xml += `    <wp:author>
      <wp:author_id>${user.id}</wp:author_id>
      <wp:author_login><![CDATA[${user.slug}]]></wp:author_login>
      <wp:author_email><![CDATA[${user.email}]]></wp:author_email>
      <wp:author_display_name><![CDATA[${user.name}]]></wp:author_display_name>
      <wp:author_first_name><![CDATA[]]></wp:author_first_name>
      <wp:author_last_name><![CDATA[]]></wp:author_last_name>
    </wp:author>\n`;
    });

    // Add Tags as WordPress Categories/Tags
    tags.forEach(tag => {
        xml += `    <wp:tag>
      <wp:term_id>${tag.id}</wp:term_id>
      <wp:tag_slug><![CDATA[${tag.slug}]]></wp:tag_slug>
      <wp:tag_name><![CDATA[${tag.name}]]></wp:tag_name>
    </wp:tag>\n`;
    });

    posts.forEach(post => {
        const postDate = new Date(post.published_at || post.created_at);
        const dateStr = formatDate(postDate);
        const gmtDateStr = formatDate(postDate); // Simplified: assuming input is UTC

        // Get author for this post
        const postAuthorRel = posts_authors.find(pa => pa.post_id === post.id);
        const authorId = postAuthorRel ? postAuthorRel.author_id : post.author_id;
        const author = userMap.get(authorId || "") || users[0] || { slug: 'admin' };

        xml += `    <item>
      <title><![CDATA[${post.title}]]></title>
      <link></link>
      <pubDate>${postDate.toUTCString()}</pubDate>
      <dc:creator><![CDATA[${author.slug || 'admin'}]]></dc:creator>
      <guid isPermaLink="false"></guid>
      <description></description>
      <content:encoded><![CDATA[${post.html || post.markdown || ""}]]></content:encoded>
      <excerpt:encoded><![CDATA[${post.custom_excerpt || ""}]]></excerpt:encoded>
      <wp:post_id>${post.id}</wp:post_id>
      <wp:post_date><![CDATA[${dateStr}]]></wp:post_date>
      <wp:post_date_gmt><![CDATA[${gmtDateStr}]]></wp:post_date_gmt>
      <wp:comment_status><![CDATA[closed]]></wp:comment_status>
      <wp:ping_status><![CDATA[closed]]></wp:ping_status>
      <wp:post_name><![CDATA[${post.slug}]]></wp:post_name>
      <wp:status><![CDATA[${post.status === 'published' ? 'publish' : 'draft'}]]></wp:status>
      <wp:post_parent>0</wp:post_parent>
      <wp:menu_order>0</wp:menu_order>
      <wp:post_type><![CDATA[${post.type === 'page' ? 'page' : 'post'}]]></wp:post_type>
      <wp:post_password><![CDATA[]]></wp:post_password>
      <wp:is_sticky>${post.featured ? 1 : 0}</wp:is_sticky>
`;

        // Add associated tags
        posts_tags.filter(pt => pt.post_id === post.id).forEach(pt => {
            const tag = tagMap.get(pt.tag_id);
            if (tag) {
                xml += `      <category domain="post_tag" nicename="${tag.slug}"><![CDATA[${tag.name}]]></category>\n`;
            }
        });

        // Add metadata like featured image if it exists
        if (post.feature_image) {
            xml += `      <wp:postmeta>
        <wp:meta_key><![CDATA[_thumbnail_id]]></wp:meta_key>
        <wp:meta_value><![CDATA[${post.feature_image}]]></wp:meta_value>
      </wp:postmeta>\n`;
        }

        xml += `    </item>\n`;
    });

    xml += `  </channel>
</rss>`;

    return xml;
};
